config/routes.rb
Rails.application.routes.draw do
  resources :quotes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'authors#index'
  get '/authors', to: 'authors#index'
  get '/authors/new', to: 'authors#new', as: 'new_author'
  get '/authors/:slug', to: 'authors#show'
  post '/authors', to: 'authors#create'
  get '/authors/:slug/edit', to: 'authors#edit', as: 'author'
  patch '/authors/:id/edit', to: 'authors#update'
  delete '/authors/:slug', to: 'authors#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
	before_action :set_author_by_slug, only: [:show, :edit, :destroy]
	def index
		@authors = Author.all
	end

	def show
		@quotes = Quote.where(author: @author.author_name)
	end

	def new
		@author = Author.new
	end

	def create
		@author = Author.new(author_params)
		@author.save
		redirect_to "/authors/#{@author.slug}"
	end

	def edit
	end

	def update
		@author = Author.find(params[:id])
		@author.update(author_params)
		redirect_to "/authors/#{@author.slug}"
	end

	def destroy
		@author.destroy
		redirect_to '/authors'
	end

	private

	  def author_params
		  params.require(:author).permit(:author_name, :year_of_birth, :birthplace, :description, :slug)
	  end

	  def set_author_by_slug
	  	@author = Author.find_by(slug: params[:slug])
	  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:author, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/authors/_form.html.erb
<div align="center">
<%= form_for(author) do |form| %>
	<div class="field">
		<%= form.text_field :author_name, placeholder: "Author Name" %>
	</div>
	<br>
	<div class="field">
		<%= form.text_field :year_of_birth, placeholder: "Year of Birth" %>
	</div>
		<br>

	<div class="field">
		<%= form.text_field :birthplace, placeholder: "Birthplace" %>
	</div>
		<br>

	<div class="field">
		<%= form.text_area :description, placeholder: "Description" %>
	</div>
		<br>

	<div class="field">
		<%= form.text_field :slug, placeholder: "Slug" %>
	</div>
		<br>

	<div>
		<%= form.submit 'Create Author', :class => 'btn btn-lg btn-success' %>&ensp;
		<a class="btn btn-secondary btn-lg" href="/authors">Back</a>
	</div>

<% end %>
</div>

app/views/authors/edit.html.erb
<br>
<br>
<br>
<br>
<br>

<h1 align="center"> Edit Author </h1>
<br>
<%= render 'form', author: @author %>

app/views/authors/index.html.erb
<br>
<br>
<h1 align="center">Authors</h1>
<br>
<div align="center">
<%= link_to 'New Author', new_author_path, class: "btn btn-info btn-lg" %> &ensp; <%= link_to 'Quotes', quotes_path, class: "btn btn-secondary btn-lg" %>
</div>
<br>
<br />
<br />
<br />
<br />
<div class="row" style="max-width: 1300px; margin: auto;">
<% @authors.each do |author| %>
  <div class="col-sm-3">
  	<a href="/authors/<%=author.slug%>">
    <div class="card" style="margin: 20px;">
<!--       <img class="card-img-top" src="assets/#{author.slug}.jpg" alt="Card image cap">
 -->  <div class="card-body"  align="center">
        <h5 class="card-title" ><%= author.author_name %></h5>
        <p class="card-text" style="color: #4d4d4d;">Born in <%= author.year_of_birth %> </p>
      </div>
      <div class="card-footer">
      <small class="text-muted"> <%= author.birthplace %></small>
      </div>
    </div>
    </a>
  </div>
<% end %>
</div>





<br>

app/views/authors/new.html.erb
<br>
<br>
<br>
<br>
<br>

<h1 align="center"> New Author </h1>
<br>

<%= render 'form', author: @author %>

app/views/authors/show.html.erb
<br>
<h1 align="center"> <%= @author.author_name %> </h1>
<p style="max-width: 1000px; margin: auto;">
   <%= @author.description %>
</p>
<br>
<div align="center">
<a class="btn btn-info btn-lg" href="/authors/<%=@author.slug%>/edit">Edit</a> &ensp;
<%= link_to 'Delete', "/authors/#{@author.slug}", method: :delete, class: "btn btn-danger btn-lg" %> &ensp;
<a class="btn btn-secondary btn-lg" href="/authors">Back</a>
</div>
<br>
<h2 align="center">Quotes</h2>


<div class="card-columns" style="column-count: 4; margin: 30px;">
  <% @quotes.each do |quote| %>
      <a href="/quotes/<%= quote.id %>" class="card p-3" style="color: #4d4d4d;">
        <blockquote class="blockquote mb-0 ">
          <p class="text-center"><%= quote.text %></p>
          <footer class="blockquote-footer text-right">
            <small class="text-muted "> <%= quote.author %>
            </small>
          </footer>
        </blockquote>
      </a>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuoteMee</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quotes/_form.html.erb
<%= form_with(model: quote, local: true) do |form| %>
  <% if quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" align="center">
    <%= form.text_field :author, placeholder: "Author" %>
  </div>
<br>
  <div class="field" align="center">
    <%= form.text_area :text, placeholder: "Description" %>
  </div>
<br>
  <div class="actions" align="center">
    <%= form.submit 'Create Quote', :class => "btn btn-lg btn-success" %> &ensp;
    <a class="btn btn-secondary btn-lg" href="/quotes">Back</a>

  </div>
<% end %>

app/views/quotes/edit.html.erb
<br>
<br>
<br>
<br>
<br>

<h1 align="center">Edit Quote</h1>
<br>
<%= render 'form', quote: @quote %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">Quotes</h1>

<br>
<div align="center">
<%= link_to 'New Quote', new_quote_path, class: "btn btn-info btn-lg" %> &ensp; <%= link_to 'Authors', authors_path, class: "btn btn-secondary btn-lg" %>
</div>
<br>

<div class="card-columns" style="column-count: 4; margin: 30px;">
  <% @quotes.each do |quote| %>
      <a  href="/quotes/<%= quote.id %>" class="card p-3" style="color: #4d4d4d;">
        <blockquote class="blockquote mb-0 ">
          <p class="text-center"><%= quote.text %></p>
          <footer class="blockquote-footer text-right">
            <small class="text-muted "> <%= quote.author %>
            </small>
          </footer>
        </blockquote>
      </a>
  <% end %>
</div>

app/views/quotes/new.html.erb
<br>
<br>
<br>
<br>
<br>
<h1 align="center">New Quote</h1>
<br>
<%= render 'form', quote: @quote %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>


<br>
<br>
<br>
<div class="card" style="margin: 80px;">
  <div class="card-header">
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0 text-center">
      <p>  <%= @quote.text %></p>
      <footer class="blockquote-footer text-right"><%= @quote.author %></footer>
    </blockquote>
  </div>
</div>

<div align="center">
	<a class="btn btn-info btn-lg" href="/quotes/<%= @quote.id %>/edit">Edit</a> &ensp;
	<%= link_to 'Destroy', @quote, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-lg" %>&ensp;
    <a class="btn btn-secondary btn-lg" href="/quotes">Back</a>

</div>